.TH DMEVENTD 8 "Aug 18 2008"
.SH NAME
dmeventd \- Device-mapper event monitoring daemon.
.SH SYNOPSIS
.ad l
.B dmeventd
.I [-V|-d|-h]
.ad b
.SH DESCRIPTION
dmeventd is the event monitoring daemon for device-mapper devices.
.SH OPTIONS
.TP
.B -V
Show version of dmeventd
.TP
.B -d
Don't fork, run in the foreground
.TP
.B -h
Display command-line arguments
.SH AUTHORS
Original author: Joe Thornber (thornber@sistina.com)
.PP
This manual page was written by Luke Yelavich <themuso@ubuntu.com>, for the Ubuntu project (but may be used by others).

.SH SEE ALSO
Device-mapper resource page: http://sources.redhat.com/dm/
