#!/bin/sh

PREREQ="udev"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/lvm ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

if [ -e /etc/lvm/lvm.conf ]; then
	mkdir -p ${DESTDIR}/etc/lvm
	cp /etc/lvm/lvm.conf ${DESTDIR}/etc/lvm/
fi

mkdir -p $DESTDIR/lib/udev/rules.d/
for rules in 56-lvm.rules 60-persistent-storage-lvm.rules 85-lvm2.rules; do
	if   [ -e /etc/udev/rules.d/$rules ]; then
		cp -p /etc/udev/rules.d/$rules $DESTDIR/lib/udev/rules.d/
	elif [ -e /lib/udev/rules.d/$rules ]; then
		cp -p /lib/udev/rules.d/$rules $DESTDIR/lib/udev/rules.d/
	fi
done

copy_exec /sbin/dmsetup
copy_exec /sbin/lvm
ln -s lvm ${DESTDIR}/sbin/vgchange

for x in dm_mod dm_snapshot dm_mirror; do
	manual_add_modules ${x}
done
